version : "3.7"
services:
  db:
    image: mysql
    container_name: spring-db
    env_file:
      - .env.dev
    ports:
      - "3307:3306"
    volumes:
      - ./dockerDB:/app
  spring-rest-api:
    container_name: spring-rest-api
    build:
      context: ./glee-interfaces
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
#    volumes:
#      - ./wait-for-it.sh:/app/wait-for-it.sh
#    command:
#      - sh -c "/app/wait-for-it.sh db:3306 -t 60 -- java -jar /app/app.jar"