version : "3.7"
services:
  db:
    image: mysql
    container_name: spring-db
    env_file:
      - .env.local
    ports:
      - "3307:3306"
    volumes:
      - ./dockerDB:/app
  spring-rest-api:
    container_name: spring-rest-api
    build:
      context: ./glee-interfaces
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db