spring:
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glee_local?serverTimezone=Asia/Seoul
    username: root
    password: 9815chs!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: true # 기본값 true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: bd8af8022a3125fc75fcfc823eb06993
            client-secret: vrguGOWawmzOCXAhDlZ3UZqjWTvRYlhu
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            #            scope: profile_nickname,account_email,profile_image,gender,age_range
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#  jackson:
#    deserialization:
#      fail-on-ignored-properties: false

jwt:
  secret: 4lkjsdf84kvcdf14jzdsafjkdlsfdskfjsdognepopgoerignodnvofdgnoernp
  expiration: 86400 # 24 hours (임시)
  token-prefix: "Bearer "
  header-string: Authorization
